### ISSUE TITLE
Not compatible with ScalaJs 1.0.0-M1

### ISSUE THREAD

**Issue by dstibbe** [vmunier/sbt-web-scalajs#39]
When trying to use the latest plugin in combination with "org.scala-js" % "sbt-scalajs" % "1.0.0-M1", the following error occurs:

```
[info] Loading global plugins from /home/dstibbe/.sbt/0.13/plugins
[info] Loading project definition from /home/dstibbe/projects/dare-seed/project
java.lang.NoSuchMethodError: org.scalajs.sbtplugin.ScalaJSPlugin$.autoImport()Lorg/scalajs/sbtplugin/ScalaJSPlugin$AutoImport$;
        at webscalajs.ScalaJSWeb$.projectSettings(ScalaJSWeb.scala:21)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1$$anonfun$apply$34.apply(Load.scala:721)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1.apply(Load.scala:721)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$autoPluginSettings$1$1.apply(Load.scala:721)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$resolveProject$1.autoPluginSettings$1(Load.scala:720)
        at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:739)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$sbt$Load$$anonfun$$expandSettings$1$2.apply(Load.scala:740)
        at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
        at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
        at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:138)
        at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:105)
        at sbt.Load$$anonfun$resolveProject$1.sbt$Load$$anonfun$$expandSettings$1(Load.scala:740)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
        at sbt.Load$$anonfun$resolveProject$1$$anonfun$56.apply(Load.scala:743)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:742)
        at sbt.Load$$anonfun$resolveProject$1.apply(Load.scala:703)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.resolveProject(Load.scala:703)
        at sbt.Load$.sbt$Load$$finalizeProject$1(Load.scala:603)
        at sbt.Load$.discoverAndLoad$1(Load.scala:620)
        at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:629)
        at sbt.Load$.sbt$Load$$loadTransitive(Load.scala:644)
        at sbt.Load$$anonfun$loadUnit$1.sbt$Load$$anonfun$$loadProjects$1(Load.scala:482)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1$$anonfun$40.apply(Load.scala:485)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:485)
        at sbt.Load$$anonfun$loadUnit$1.apply(Load.scala:459)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.loadUnit(Load.scala:459)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:311)
        at sbt.Load$$anonfun$25$$anonfun$apply$14.apply(Load.scala:310)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:91)
        at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:90)
        at sbt.BuildLoader.apply(BuildLoader.scala:140)
        at sbt.Load$.loadAll(Load.scala:365)
        at sbt.Load$.loadURI(Load.scala:320)
        at sbt.Load$.load(Load.scala:316)
        at sbt.Load$.load(Load.scala:305)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$$anonfun$4.apply(Load.scala:146)
        at sbt.Load$.timed(Load.scala:1025)
        at sbt.Load$.apply(Load.scala:146)
        at sbt.Load$.defaultLoad(Load.scala:39)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:503)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:503)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:495)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
        at sbt.Command$.process(Command.scala:93)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
        at sbt.State$$anon$1.runCmd$1(State.scala:183)
        at sbt.State$$anon$1.process(State.scala:187)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.MainLoop$.next(MainLoop.scala:96)
        at sbt.MainLoop$.run(MainLoop.scala:89)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
        at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
        at sbt.Using.apply(Using.scala:24)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
        at sbt.MainLoop$.runLogged(MainLoop.scala:22)
        at sbt.StandardMain$.runManaged(Main.scala:61)
        at sbt.xMain.run(Main.scala:35)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
        at xsbt.boot.Launch$.run(Launch.scala:109)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
        at xsbt.boot.Launch$.launch(Launch.scala:117)
        at xsbt.boot.Launch$.apply(Launch.scala:18)
        at xsbt.boot.Boot$.runImpl(Boot.scala:41)
        at xsbt.boot.Boot$.main(Boot.scala:17)
        at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: org.scalajs.sbtplugin.ScalaJSPlugin$.autoImport()Lorg/scalajs/sbtplugin/ScalaJSPlugin$AutoImport$;
```

**Comment by sjrd** [comment]
1.x is not binary compatible with 0.6.x, so sbt plugins that depend on sbt-scalajs and want to support both need to release two separate versions, each compiled against a different version of the Scala.js sbt plugin.

**Comment by RBleyenberg** [comment]
Howdy,

I'm having the same problem... is there perhaps already a version available for the scala-js 1.0.0

cheers.

**Comment by jan0sch** [comment]
@sjrd Could you give a hint on what would need to be done to make this work with 1.0?

I guess this is related to changes in https://github.com/scala-js/scala-js/blob/master/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPlugin.scala but I'm not that deep into sbt.

**Comment by sjrd** [comment]
Start by forking, change the version of Scala.js, and fix the compile errors and whatever else needs to be fixed. Hopefully, if sbt-web-scalajs does not use deprecated features of sbt-scalajs, it should be relatively easy. The hardest part is probably to decide on a versioning/publishing scheme.

Currently on vacation, so I can't help more.

**Comment by jan0sch** [comment]
Okay, thanks for the info and have a great vacation! :-)

**Comment by jan0sch** [comment]
Folks, I'm down to one compiler error of which I have absolutely now idea how to fix here:

https://github.com/wegtam/sbt-web-scalajs/blob/scalajs-1_0/src/main/scala/webscalajs/WebScalaJS.scala#L148

```
[error] .../sbt-web-scalajs/src/main/scala/webscalajs/WebScalaJS.scala:148:87: not found: value emitSourceMaps
[error]     val projectsWithSourceMaps = filterInitializeSeq(scalaJSProjects, (p: Project) => emitSourceMaps in(p, optJS)).value
[error]                                                                                       ^
[error] one error found
```

I could see that `emitSourceMaps` has been replaced by `withSourceMap` in `scalaJSLinkerConfig` and I've already adjusted https://github.com/wegtam/sbt-web-scalajs/blob/scalajs-1_0/src/main/scala/webscalajs/ScalaJSWeb.scala accordingly.

But I have no idea how to fix this one here.

Could anyone shed some light on this?

Besides that some js packaging options were refactored into a seperate sbt plugin which was easily solveable by adding the missing dependency and import.

After fixing this the next point would be to find a way to make this co-exist with the scalajs-0.6 branch and howto cross publish...

**Comment by vmunier** [comment]
It looks like `scalaJSLinkerConfig` needs to be used to get the `sourceMap` value.
Try the following snippet of code:
```
val projectsWithSourceMaps = filterInitializeSeq(
  scalaJSProjects,
  (p: Project) => Def.setting((scalaJSLinkerConfig in p).value.sourceMap)).value
```

**Comment by jan0sch** [comment]
Worked like a charm, thank you. All compiler errors are fixed now.

How shall we proceed?

**Comment by jan0sch** [comment]
There are some issues with the tests (https://travis-ci.org/wegtam/sbt-web-scalajs/builds/346655737). I'll take a look at it when there is time.

**Comment by vmunier** [comment]
Thanks a lot @jan0sch, I created a pull request from the work you have done and I did some changes to fix the tests: https://github.com/vmunier/sbt-web-scalajs/pull/45.
I still need to figure out a versioning scheme for sbt-web-scalajs, because we now need to publish a version that uses Scala.js v0.6.22 and another version that uses Scala.js v1.0.0-M3.

**Comment by vmunier** [comment]
@randm-ch We still need to decide on a versioning scheme for sbt-web-scalajs to cross-publish to Scala.js v0.6.x and Scala.js v1.0.x.

**Comment by sjrd** [comment]
One way to do it would be to use even version numbers targeting 0.6.x, and odd numbers targeting 1.x.

**Comment by randm-ch** [comment]
@vmunier IMHO the suggestion by @sjrd is sound. The README would have to be updated in any case.
Other options may be (just from the top of my head):

`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8-1.0")` vs
`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8-0.6")`

`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8")` vs
`addSbtPlugin("com.vmunier" % "sbt-web-scalajs-0.6" % "1.0.8")`

`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8")` vs
`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.8-0.6")`

`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.1.0")` vs
`addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.2.0")`

**Comment by jan0sch** [comment]
Sounds reasonable. Would be great to bring this finally into the wild. :+1:

**Comment by vmunier** [comment]
Thanks for the suggestions!

Even though it's not a standard way to define versions, I quite like "1.0.8-1"/"1.0.8-0.6", because we can see which version depends on Scala.js v1.x or Scala.js v.0.6.x.

Using even/odd numbers sounds reasonable, I fear that some users might try to bump the library version in their build.sbt to see if a new version is available, without realising that the library depends on another major version of Scala.js.
